/**
 * @fileoverview gRPC-Web generated client stub for server
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: server.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.server = require('./server_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.server.UserServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.server.UserServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.server.UserInfo,
 *   !proto.server.UserResponse>}
 */
const methodDescriptor_UserService_Register = new grpc.web.MethodDescriptor(
  '/server.UserService/Register',
  grpc.web.MethodType.UNARY,
  proto.server.UserInfo,
  proto.server.UserResponse,
  /**
   * @param {!proto.server.UserInfo} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.server.UserResponse.deserializeBinary
);


/**
 * @param {!proto.server.UserInfo} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.server.UserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.server.UserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.server.UserServiceClient.prototype.register =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/server.UserService/Register',
      request,
      metadata || {},
      methodDescriptor_UserService_Register,
      callback);
};


/**
 * @param {!proto.server.UserInfo} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.server.UserResponse>}
 *     Promise that resolves to the response
 */
proto.server.UserServicePromiseClient.prototype.register =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/server.UserService/Register',
      request,
      metadata || {},
      methodDescriptor_UserService_Register);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.server.UserInfo,
 *   !proto.server.UserResponse>}
 */
const methodDescriptor_UserService_Login = new grpc.web.MethodDescriptor(
  '/server.UserService/Login',
  grpc.web.MethodType.UNARY,
  proto.server.UserInfo,
  proto.server.UserResponse,
  /**
   * @param {!proto.server.UserInfo} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.server.UserResponse.deserializeBinary
);


/**
 * @param {!proto.server.UserInfo} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.server.UserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.server.UserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.server.UserServiceClient.prototype.login =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/server.UserService/Login',
      request,
      metadata || {},
      methodDescriptor_UserService_Login,
      callback);
};


/**
 * @param {!proto.server.UserInfo} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.server.UserResponse>}
 *     Promise that resolves to the response
 */
proto.server.UserServicePromiseClient.prototype.login =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/server.UserService/Login',
      request,
      metadata || {},
      methodDescriptor_UserService_Login);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.server.UserInfo,
 *   !proto.server.UserResponse>}
 */
const methodDescriptor_UserService_Logout = new grpc.web.MethodDescriptor(
  '/server.UserService/Logout',
  grpc.web.MethodType.UNARY,
  proto.server.UserInfo,
  proto.server.UserResponse,
  /**
   * @param {!proto.server.UserInfo} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.server.UserResponse.deserializeBinary
);


/**
 * @param {!proto.server.UserInfo} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.server.UserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.server.UserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.server.UserServiceClient.prototype.logout =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/server.UserService/Logout',
      request,
      metadata || {},
      methodDescriptor_UserService_Logout,
      callback);
};


/**
 * @param {!proto.server.UserInfo} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.server.UserResponse>}
 *     Promise that resolves to the response
 */
proto.server.UserServicePromiseClient.prototype.logout =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/server.UserService/Logout',
      request,
      metadata || {},
      methodDescriptor_UserService_Logout);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.server.MessageServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.server.MessageServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.server.Message,
 *   !proto.server.MessageResponse>}
 */
const methodDescriptor_MessageService_SendMessage = new grpc.web.MethodDescriptor(
  '/server.MessageService/SendMessage',
  grpc.web.MethodType.UNARY,
  proto.server.Message,
  proto.server.MessageResponse,
  /**
   * @param {!proto.server.Message} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.server.MessageResponse.deserializeBinary
);


/**
 * @param {!proto.server.Message} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.server.MessageResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.server.MessageResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.server.MessageServiceClient.prototype.sendMessage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/server.MessageService/SendMessage',
      request,
      metadata || {},
      methodDescriptor_MessageService_SendMessage,
      callback);
};


/**
 * @param {!proto.server.Message} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.server.MessageResponse>}
 *     Promise that resolves to the response
 */
proto.server.MessageServicePromiseClient.prototype.sendMessage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/server.MessageService/SendMessage',
      request,
      metadata || {},
      methodDescriptor_MessageService_SendMessage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.server.Empty,
 *   !proto.server.Message>}
 */
const methodDescriptor_MessageService_StreamMessages = new grpc.web.MethodDescriptor(
  '/server.MessageService/StreamMessages',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.server.Empty,
  proto.server.Message,
  /**
   * @param {!proto.server.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.server.Message.deserializeBinary
);


/**
 * @param {!proto.server.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.server.Message>}
 *     The XHR Node Readable Stream
 */
proto.server.MessageServiceClient.prototype.streamMessages =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/server.MessageService/StreamMessages',
      request,
      metadata || {},
      methodDescriptor_MessageService_StreamMessages);
};


/**
 * @param {!proto.server.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.server.Message>}
 *     The XHR Node Readable Stream
 */
proto.server.MessageServicePromiseClient.prototype.streamMessages =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/server.MessageService/StreamMessages',
      request,
      metadata || {},
      methodDescriptor_MessageService_StreamMessages);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.server.Empty,
 *   !proto.server.UserJoin>}
 */
const methodDescriptor_MessageService_NotifyUserJoin = new grpc.web.MethodDescriptor(
  '/server.MessageService/NotifyUserJoin',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.server.Empty,
  proto.server.UserJoin,
  /**
   * @param {!proto.server.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.server.UserJoin.deserializeBinary
);


/**
 * @param {!proto.server.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.server.UserJoin>}
 *     The XHR Node Readable Stream
 */
proto.server.MessageServiceClient.prototype.notifyUserJoin =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/server.MessageService/NotifyUserJoin',
      request,
      metadata || {},
      methodDescriptor_MessageService_NotifyUserJoin);
};


/**
 * @param {!proto.server.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.server.UserJoin>}
 *     The XHR Node Readable Stream
 */
proto.server.MessageServicePromiseClient.prototype.notifyUserJoin =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/server.MessageService/NotifyUserJoin',
      request,
      metadata || {},
      methodDescriptor_MessageService_NotifyUserJoin);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.server.Empty,
 *   !proto.server.UserLeave>}
 */
const methodDescriptor_MessageService_NotifyUserLeave = new grpc.web.MethodDescriptor(
  '/server.MessageService/NotifyUserLeave',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.server.Empty,
  proto.server.UserLeave,
  /**
   * @param {!proto.server.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.server.UserLeave.deserializeBinary
);


/**
 * @param {!proto.server.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.server.UserLeave>}
 *     The XHR Node Readable Stream
 */
proto.server.MessageServiceClient.prototype.notifyUserLeave =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/server.MessageService/NotifyUserLeave',
      request,
      metadata || {},
      methodDescriptor_MessageService_NotifyUserLeave);
};


/**
 * @param {!proto.server.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.server.UserLeave>}
 *     The XHR Node Readable Stream
 */
proto.server.MessageServicePromiseClient.prototype.notifyUserLeave =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/server.MessageService/NotifyUserLeave',
      request,
      metadata || {},
      methodDescriptor_MessageService_NotifyUserLeave);
};


module.exports = proto.server;

