/**
 * @fileoverview gRPC-Web generated client stub for server
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: server.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.server = require('./server_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.server.ServerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.server.ServerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.server.Message,
 *   !proto.server.MessageResponse>}
 */
const methodDescriptor_Server_GetServerResponse = new grpc.web.MethodDescriptor(
  '/server.Server/GetServerResponse',
  grpc.web.MethodType.UNARY,
  proto.server.Message,
  proto.server.MessageResponse,
  /**
   * @param {!proto.server.Message} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.server.MessageResponse.deserializeBinary
);


/**
 * @param {!proto.server.Message} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.server.MessageResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.server.MessageResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.server.ServerClient.prototype.getServerResponse =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/server.Server/GetServerResponse',
      request,
      metadata || {},
      methodDescriptor_Server_GetServerResponse,
      callback);
};


/**
 * @param {!proto.server.Message} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.server.MessageResponse>}
 *     Promise that resolves to the response
 */
proto.server.ServerPromiseClient.prototype.getServerResponse =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/server.Server/GetServerResponse',
      request,
      metadata || {},
      methodDescriptor_Server_GetServerResponse);
};


module.exports = proto.server;

